name: Package Windows Engines (AVX512)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------------------------------------
      # 1️⃣ Prepare directories
      # ----------------------------------------------------------
      - name: Create directories
        run: mkdir -p engines licenses

      # ----------------------------------------------------------
      # 2️⃣ Download Caïssa (binary + weights + license)
      # ----------------------------------------------------------
      - name: Download Caïssa
        run: |
          mkdir -p engines/caissa
          echo "⬇️  Downloading Caïssa engine..."
          curl -L -o engines/caissa/caissa-1.23-x64-avx512.exe \
            https://github.com/Witek902/Caissa/releases/download/1.23/caissa-1.23-x64-avx512.exe

          echo "⬇️  Downloading Caïssa neural network weights..."
          curl -L -o engines/caissa/eval-65.pnn \
            https://raw.githubusercontent.com/Witek902/Caissa/master/data/neuralNets/eval-65.pnn

          echo "⬇️  Downloading Caïssa license..."
          curl -L -o engines/caissa/LICENSE \
            https://raw.githubusercontent.com/Witek902/Caissa/master/LICENSE || echo "License unavailable" > engines/caissa/LICENSE

          echo "🧩 Copying config.json..."
          cp configs/caissa.json engines/caissa/config.json
          sed -i 's/"engine": *"[^"]*"/"engine": "caissa-1.23-x64-avx512.exe"/' engines/caissa/config.json

          echo "✅ Caïssa packaging ready:"
          ls -lh engines/caissa

      # ----------------------------------------------------------
      # 3️⃣ Download Patricia
      # ----------------------------------------------------------
      - name: Download Patricia
        run: |
          mkdir -p engines/patricia
          echo "⬇️  Downloading Patricia..."
          curl -L -o engines/patricia/patricia_v3-avx512.exe \
            https://github.com/Adam-Kulju/Patricia/releases/download/5/patricia_v3.exe
          curl -L -o engines/patricia/LICENSE \
            https://raw.githubusercontent.com/Adam-Kulju/Patricia/master/LICENSE || echo "MIT License" > engines/patricia/LICENSE
          cp configs/patricia.json engines/patricia/config.json
          sed -i 's/"engine": *"[^"]*"/"engine": "patricia_v3-avx512.exe"/' engines/patricia/config.json

      # ----------------------------------------------------------
      # 4️⃣ Download Stockfish (extract + license)
      # ----------------------------------------------------------
      - name: Download Stockfish
        run: |
          mkdir -p engines/stockfish
          echo "⬇️  Downloading Stockfish..."
          curl -L -o engines/stockfish/stockfish-avx512.zip \
            https://github.com/official-stockfish/Stockfish/releases/download/sf_17.1/stockfish-windows-x86-64-avx512.zip

          echo "📦 Extracting archive..."
          unzip -q engines/stockfish/stockfish-avx512.zip -d engines/stockfish/tmp

          # Handles both layouts gracefully
          FOUND_EXE=$(find engines/stockfish/tmp -type f -name "stockfish*.exe" | head -n 1)
          if [ -z "$FOUND_EXE" ]; then
            echo "❌ Could not locate Stockfish executable after unzip"
            find engines/stockfish/tmp -maxdepth 4
            exit 1
          fi
          echo "✅ Found: $FOUND_EXE"
          mv "$FOUND_EXE" engines/stockfish/stockfish-windows-x86-64-avx512.exe

          # Clean up
          rm -rf engines/stockfish/tmp engines/stockfish/stockfish-avx512.zip

          # Add license + config
          curl -L -o engines/stockfish/LICENSE \
            https://raw.githubusercontent.com/official-stockfish/Stockfish/master/Copying.txt

          cp configs/stockfish.json engines/stockfish/config.json
          sed -i 's/"engine": *"[^"]*"/"engine": "stockfish-windows-x86-64-avx512.exe"/' engines/stockfish/config.json

      # ----------------------------------------------------------
      # 5️⃣ Package each engine individually
      # ----------------------------------------------------------
      - name: Create ZIPs
        run: |
          cd engines
          zip -r caissa-windows-avx512.zip caissa
          zip -r patricia-windows-avx512.zip patricia
          zip -r stockfish-windows-avx512.zip stockfish
          ls -lh *.zip

      # ----------------------------------------------------------
      # 6️⃣ Upload to GitHub Release
      # ----------------------------------------------------------
      - name: Upload engine ZIPs to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            engines/caissa-windows-avx512.zip
            engines/patricia-windows-avx512.zip
            engines/stockfish-windows-avx512.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

